apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus

  - name: grafana-postgresql-datasource
    type: postgres
    access: proxy
    uid: savh_postgres
    url: ${GRAFANA_PG_HOST}:${GRAFANA_PG_PORT}
    database: ${GRAFANA_PG_DB}
    user: ${GRAFANA_PG_USER}
    secureJsonData:
      password: ${GRAFANA_PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
